### ISSUE TITLE
All users loose room connection after 10 minutes

### ISSUE THREAD

**Issue by mik13ST** [RobertLemmens/youtube-sync#10]
Hello. All users (two) loose room connection seemingly around 10 minutes after creating the room. That's a problem because then the playback or chat isn't synced anymore so a manual reconnect is needed by reloading the page etc. Furthermore, the video keeps playing if it disconnects.
This is how the chat looks like when it happens:
![image](https://github.com/RobertLemmens/youtube-sync/assets/19293769/0e5fe892-fe98-4d22-b9f5-9151b3c2d2c5)

This is the JavaScript log:
![image](https://github.com/RobertLemmens/youtube-sync/assets/19293769/368d14ae-3c8a-4f2e-9647-89079f3cddee)
These three play.google.com request errors showed up right after it happened and more identical errors are happening every few seconds. 

What I'd like:
- prevent periodic 10 minute disconnects
- stop video on disconnect

Is this enough for you to find the problem? I could do a git bisect to find out which commit is causing this. It wasn't happening the last time I used the app (sometime in 2021). I would have to run the server on my machine though.

Thanks for keeping this app online even after the years.

**Comment by RobertLemmens** [comment]
Hey mik13ST, thank you for reporting. 

I probably know why this is happening on the live site. It's something with the hosting provider where i spin all my stuff. It actually scales down the backend to 0 before bringing it back up after some time, losing all state. I will disable this, should be fixed somewhere monday.

**Comment by mik13ST** [comment]
Sorry for late reply, but it keeps happening.

Any other ideas? I can try to replicate it locally and see which commit caused it, if it's caused by code changes that is.

**Comment by RobertLemmens** [comment]
Sorry for the delay. I think the issue should be fixed now. I just tried it and was still in after 20 minutes. the old loadbalancer was still active somehow.

**Comment by mik13ST** [comment]
Yes, it seems to work now after 18 minutes of testing. Thanks.
