### ISSUE TITLE
build.sh doesn't stop on error

### ISSUE THREAD

**Issue by mik13ST** [RobertLemmens/youtube-sync#11]
I am trying to run the app to try to solve #10 by running the build.sh script. I get `exec /usr/bin/sbt: exec format error` but then it continues and later I get ` => ERROR [2/2] COPY backend/target/scala-2.12/backend-assembly-*.jar app.jar`.

The build.sh looks like this:
```bash
#!/bin/sh
docker run -it --rm -v $PWD:/app -w /app mozilla/sbt sbt "project backend" assembly
docker build -t rlemmens/youtube-sync:latest .
```

When I ran the first command manually, it failed with the `exec format error` and the exit code of it was 1. I suggest adding `set -e` to the top of the script so it stops when one of the commands fails. Also, it's probably a good idea to add `set -u` to treat unset shell variables as errors. See https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html for details.

**Comment by RobertLemmens** [comment]
yes this is a good idea to add. thanks for the report..
