### ISSUE TITLE
Support for short YouTube links

### ISSUE THREAD

**Issue by mik13ST** [RobertLemmens/youtube-sync#2]
I noticed the app doesn't accept short YouTube links. Maybe they should be supported too. Some people are used to sharing videos using the share button only.

What I did:
1. pasted `https://youtu.be/xy_NKN75Jhw` into the text field for adding a video
2. pressed the "Add video" button

What I expected:
The video would be added into the playlist.

What happened instead:
Nothing happened.

Is it possible to add support for these links?

**Comment by RobertLemmens** [comment]
thanks for reporting.

test version with short url support running at http://youtube-sync-r-lemmens-dev.apps.sandbox.x8i5.p1.openshiftapps.com/

Merging it to master later this weekend!

**Comment by mik13ST** [comment]
The test version at the URL seems to work for the short URLs and for the normal URLs too. Would +1 the PR, but I cannot (or I just don't know GitHub well enough, never done a PR review).

**Comment by RobertLemmens** [comment]
fixed in #3
